### ISSUE TITLE
Feature Request: Tages-Gesamt-Menge als Bar-Chart

### ISSUE THREAD

**Issue by wico-heuschkel** [zreptil/nightscout-reporter-angular#1]
Ich fände es super, wenn man einen Bar-Chart für den gewählten Zeitraum für die Tagesmenge an Inusin bekommen könnte (also für jeden Tag eine Bar). Am besten eine gestapelte Bar die zwischen Basal Und Bolus unterscheidet.

LG

**Comment by zreptil** [comment]
So etwas gibt es schon in der Tagesstatistik. Das sieht dann so aus:

![image](https://github.com/zreptil/nightscout-reporter-angular/assets/6327589/96f29f6a-b637-447b-a66a-ab79bbf6455f)

Die blauen Balken in der zweiten Spalte stellen die jeweilige Insulinmenge prozentual dar, in den Spalten 6 bis 8 stehen die jeweiligen Werte für die Insuline. Ist das etwas, was Dir weiter hilft?

**Comment by wico-heuschkel** [comment]
Hi,
danke für die schnelle Antwort!
Jein ich würde gern grafisch sehen ob ich Phasen habe, in denen ich mehr Insulin brauche. 

Ich habe in der "Zeitraum Auswertung" die mittlere Grafik entdeckt. Wenn man die Kohlenhydrate und BZ Werte abstellt ist es genau was ich suche. Ich denke ich kann da einfach mehrere Exporte habe und mir die PDF dann so zurecht basteln wie ich es brauche!

Danke nochmal!

**Comment by wico-heuschkel** [comment]
Oh wow ein wahrer Traum! Dankeschön!
