### ISSUE TITLE
Deployment nicht im root Verzeichnis des Webservers

### ISSUE THREAD

**Issue by gruoner** [zreptil/nightscout-reporter-angular#2]
Wie kriege ich den Nightscout Reporter woanders auf dem Webserver installiert als im root Verzeichnis.
Gibt es dafür bereits irgendwo im Code eine Base-URL oder so? Bislang werden alle Bilder, CSS und JS direkt auf dem Root Verzeichnis nachgeladen.....

**Comment by zreptil** [comment]
Das hängt vom Webserver ab, den Du verwendest. Da ich Nightscout Reporter aktuell auf einem IIS hoste, habe ich in der nightscout-reporter_local.zip eine web.config eingefügt, die damit funktioniert. Die musst Du dann vermutlich anpassen und in der index.html beim Tag <base href="..."> den richtigen Pfad eingeben. Das base href ist nötig, um Angular Projekte in Unterverzeichnissen zu hosten.

Da ich den aber selbst hoste und froh bin, dass es mit der Konfiguration funktioniert, die ich für den IIS ausgeknobelt habe, und ich nicht wirklich die Wissensinstanz für Fremdhosting auf unbekannten Systemen bin, kann ich Dir dazu nicht wesentlich mehr sagen.

**Comment by gruoner** [comment]
also habs hinbekommen und war gar nicht so kompliziert -- Doku lesen hilft
der Build muss mit
_ng build --output-path dist/nightrep --base-href /NightScoutReporter-angular/ --deploy-url /NightScoutReporter-angular/_
gemacht werden. Dann wirft es das Ding unter dist/nightrep (aber ohne ein zip-File). dist/nightrep muss dann auf dem Webserver genau unter /NightScoutReporter-angular (oder jede andere Base-URL) geworfen werden.
